<html>
  <head>
    <title>Latent Growth Curve Modeling (LGCM)</title>

    <!-- css goes here -->
    <!-- Include CDN JavaScript -->
    <script src="https://unpkg.com/tailwindcss-jit-cdn"></script>
    <!-- End css goes here -->

    <!-- Highlight.js -->

    <style type="text/css">
      code {
        white-space: pre;
      }
    </style>
    <style type="text/css">
      pre > code.sourceCode {
        white-space: pre;
        position: relative;
      }
      pre > code.sourceCode > span {
        display: inline-block;
        line-height: 1.25;
      }
      pre > code.sourceCode > span:empty {
        height: 1.2em;
      }
      code.sourceCode > span {
        color: inherit;
        text-decoration: inherit;
      }
      div.sourceCode {
        margin: 1em 0;
      }
      pre.sourceCode {
        margin: 0;
      }
      @media screen {
        div.sourceCode {
          overflow: auto;
        }
      }
      @media print {
        pre > code.sourceCode {
          white-space: pre-wrap;
        }
        pre > code.sourceCode > span {
          text-indent: -5em;
          padding-left: 5em;
        }
      }
      pre.numberSource code {
        counter-reset: source-line 0;
      }
      pre.numberSource code > span {
        position: relative;
        left: -4em;
        counter-increment: source-line;
      }
      pre.numberSource code > span > a:first-child::before {
        content: counter(source-line);
        position: relative;
        left: -1em;
        text-align: right;
        vertical-align: baseline;
        border: none;
        display: inline-block;
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        padding: 0 4px;
        width: 4em;
      }
      pre.numberSource {
        margin-left: 3em;
        padding-left: 4px;
      }
      div.sourceCode {
        color: #cccccc;
        background-color: #303030;
      }
      @media screen {
        pre > code.sourceCode > span > a:first-child::before {
          text-decoration: underline;
        }
      }
      code span.al {
        color: #ffcfaf;
      } /* Alert */
      code span.an {
        color: #7f9f7f;
        font-weight: bold;
      } /* Annotation */
      code span.at {
      } /* Attribute */
      code span.bn {
        color: #dca3a3;
      } /* BaseN */
      code span.bu {
      } /* BuiltIn */
      code span.cf {
        color: #f0dfaf;
      } /* ControlFlow */
      code span.ch {
        color: #dca3a3;
      } /* Char */
      code span.cn {
        color: #dca3a3;
        font-weight: bold;
      } /* Constant */
      code span.co {
        color: #7f9f7f;
      } /* Comment */
      code span.cv {
        color: #7f9f7f;
        font-weight: bold;
      } /* CommentVar */
      code span.do {
        color: #7f9f7f;
      } /* Documentation */
      code span.dt {
        color: #dfdfbf;
      } /* DataType */
      code span.dv {
        color: #dcdccc;
      } /* DecVal */
      code span.er {
        color: #c3bf9f;
      } /* Error */
      code span.ex {
      } /* Extension */
      code span.fl {
        color: #c0bed1;
      } /* Float */
      code span.fu {
        color: #efef8f;
      } /* Function */
      code span.im {
      } /* Import */
      code span.in {
        color: #7f9f7f;
        font-weight: bold;
      } /* Information */
      code span.kw {
        color: #f0dfaf;
      } /* Keyword */
      code span.op {
        color: #f0efd0;
      } /* Operator */
      code span.ot {
        color: #efef8f;
      } /* Other */
      code span.pp {
        color: #ffcfaf;
        font-weight: bold;
      } /* Preprocessor */
      code span.sc {
        color: #dca3a3;
      } /* SpecialChar */
      code span.ss {
        color: #cc9393;
      } /* SpecialString */
      code span.st {
        color: #cc9393;
      } /* String */
      code span.va {
      } /* Variable */
      code span.vs {
        color: #cc9393;
      } /* VerbatimString */
      code span.wa {
        color: #7f9f7f;
        font-weight: bold;
      } /* Warning */
    </style>
    <!-- End Highlight.js -->
  </head>
  <body>
    <!-- include-before -->
    <!-- End include-before -->

    <!-- custom layout -->
    <div
      class="max-w-3xl px-4 py-10 mx-auto sm:px-6 sm:py-12 lg:max-w-4xl lg:py-16 lg:px-8 xl:max-w-6xl"
    >
      <div class="flex flex-col w-full py-12 text-left lg:text-center">
        <div class="space-y-1 text-center">
          <div>
            <h1
              class="text-3xl font-extrabold text-black tracking-tight sm:text-4xl md:text-5xl md:leading-[3.5rem]"
            >
              Latent Growth Curve Modeling (LGCM)
            </h1>
            <h2
              class="text-xl text-gray-800 tracking-tight sm:text-2xl md:text-2xl md:leading-[3.5rem] italic"
            ></h2>
          </div>
        </div>
      </div>

      <!-- Tailwind Typography -->
      <article class="mx-auto prose md:prose-md lg:prose-lg">
        <!-- 
split_by: section
split_by: chapter
bookdown::gitbook
-->
        <article class="prose">
          <p>
            The latent growth model (LGM) extends CFA to the analysis of items
            across time. The LGCM approach provides a flexible strategy for
            specifying and evaluating relationships among variables that have
            been assessed repeatedly across multiple measurement occasions
            <span class="citation">[@Preacher2008]</span>. These models are
            often the go-to choice for developmental research as they allow for
            characterizing the rate (e.g., increasing, decreasing) and shape
            (e.g., linear, quadratic) of change in outcomes at both, the group-
            and individual-level.
          </p>
          <p>
            The LGCM framework can also be extended to evaluate other
            substantive questions relevant to continuity and change. This
            vignette will explore a basic (“unconditional”) LGCM, as well as
            three commonly applied extensions to this approach, as follow:
          </p>
          <!-- ... -->
        </article>

        <!-- component -->
        <ul class="flex border-b list-reset">
          <li class="mr-1 -mb-px">
            <a
              class="inline-block px-4 py-2 font-semibold bg-white border-t border-l border-r rounded-t text-blue-dark"
              href="#"
              >Active</a
            >
            test test test
          </li>
          <li class="mr-1">
            <a
              class="inline-block px-4 py-2 font-semibold bg-white text-blue hover:text-blue-darker"
              href="#"
              >Tab</a
            >
            test test
          </li>
          <li class="mr-1">
            <a
              class="inline-block px-4 py-2 font-semibold bg-white text-blue hover:text-blue-darker"
              href="#"
              >Tab</a
            >
            test
          </li>
          <li class="mr-1">
            <a
              class="inline-block px-4 py-2 font-semibold bg-white text-grey-light"
              href="#"
              >Tab</a
            >
            te
          </li>
        </ul>
        <div
          class="flex items-center p-2 rounded-lg shadow-sm bg-gradient-to-r from-yellow-400 via-red-500 to-pink-500"
        >
          <div class="p-3 mr-4">
            <p>
              <svg class="w-10 h-10 px-1 text-400" viewBox="0 0 16 16">
                <path
                  fill-rule="evenodd"
                  d="M1.75 1.5a.25.25 0 00-.25.25v9.5c0 .138.112.25.25.25h2a.75.75 0 01.75.75v2.19l2.72-2.72a.75.75 0 01.53-.22h6.5a.25.25 0 00.25-.25v-9.5a.25.25 0 00-.25-.25H1.75zM0 1.75C0 .784.784 0 1.75 0h12.5C15.216 0 16 .784 16 1.75v9.5A1.75 1.75 0 0114.25 13H8.06l-2.573 2.573A1.457 1.457 0 013 14.543V13H1.75A1.75 1.75 0 010 11.25v-9.5zM9 9a1 1 0 11-2 0 1 1 0 012 0zm-.25-5.25a.75.75 0 00-1.5 0v2.5a.75.75 0 001.5 0v-2.5z"
                ></path>
              </svg>
            </p>
          </div>
          <div>
            <p class="text-lg text-gray-700 dark:text-gray-200">
              Warning this statistical method can be a bit tricky. There is a
              subtle assumption that you should really think about and failing
              to do so will be a bad thing, so do a good thing and think about
              it.
            </p>
          </div>
        </div>
        <button
          class="px-4 py-2 font-bold text-white bg-blue-500 rounded-full hover:bg-blue-700"
        >
          Button
        </button>
        <ul>
          <li>
            <a href="lgcm-ex-1.html">5.1: LGCM w/ Continuous Indicators</a>
          </li>
          <li>
            <a href="lgcm-ex-1.html"
              >5.2: LGCM w/ Continuous Indicators with Time-Varying
              Covariates</a
            >
          </li>
          <li>
            <a href="lgcm-ex-1.html"
              >5.3: LGCM w/ Continuous Indicators Predicting Distal Outcomes</a
            >
          </li>
          <li>
            <a href="lgcm-ex-1.html"
              >5.4: LGCM w/ Continuous Indicators and Antecedent Predictors</a
            >
          </li>
          <li>
            <a href="lgcm-ex-1.html"
              >5.5: xxxxxxxxx other examples See statmodel Chpt. 6 sections</a
            >
            <br />
            <br />
          </li>
        </ul>
        <div
          id="basic-lgcm"
          class="section level2 tabset tabset-fade"
          style="color: black"
        >
          <h2 class="tabset tabset-fade" style="color: black">
            5.1: Basic LGCM
          </h2>
          <p>
            This is an example of a basic LGCM w/ continuous outcome [y], across
            four measurement occassions
          </p>
          <p><br /></p>
          <div id="text-overview" class="section level3">
            <h3><span style="color: blue">Text Overview</span></h3>
            <p>
              LGCM is a special class of confirmatory factor analysis used to
              model some outcome (Y) measured repeatedly over time (t). The most
              basic LGCM includes two latent factors and uses a fixed time
              structure to model the observed outcome (Y) across assessment
              waves (t): 1) a latent intercept; and 2) a latent slope. The
              intercept factor is constant for each individual across
              observations, and is akin to the point at which a straight line
              “intercepts” the vertical axis on a two-dimensional coordinate
              system (<span class="citation">@citation</span>). This is modeled
              by fixing the factor loadings for the latent intercept to 1 at
              each measurement occassion.
            </p>
          </div>
          <div id="diagram" class="section level3">
            <h3><span style="color: red">Diagram</span></h3>
            <div class="sourceCode" id="cb1">
              <pre
                class="sourceCode r fold-show"
              ><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example-5.1</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="st">&#39; i =~ 1*y1 + 1*y2 + 1*y3 + 1*y4</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="st">           s =~ 0*y1 + 1*y2 + 2*y3 + 3*y4 &#39;</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">growth</span>(model, <span class="at">data=</span>path<span class="sc">-</span>to<span class="sc">-</span>data)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre>
            </div>
            <p>
              A basic linear growth model includes two factors: 1) a latent
              intercept; and 2) a latent slope. This model estimates the
              following six parameters:
            </p>
            <ol style="list-style-type: decimal">
              <li>
                intercept mean (<span class="inline math">\(\[ \mu\]\)</span>i);
              </li>
              <li>
                intercept variance (<span class="inline math"
                  >\(\[ \sigma\]\)</span
                >i);
              </li>
              <li>
                slope mean (<span class="inline math">\(\[ \mu\]\)</span>s);
              </li>
              <li>
                slope variance (<span class="inline math">\(\[ \sigma\]\)</span
                >s);
              </li>
              <li>
                intercept and slope covariance (<span class="inline math"
                  >\(\[ \sigma\]\)</span
                >is); and
              </li>
              <li>
                an error variance that remains constant across repeated
                measurements (<span class="inline math">\(\[ \sigma\]\)</span>ε)
                <br />
                <br />
              </li>
            </ol>
            <p>
              This model is specified by using the ‘<em>=~</em>’ operator to
              name and define the growth model factors. The left-hand side of
              the ‘=~’ operator is used to specify the latent intercept
              <em>i</em> and latent slope <em>s</em> factors. The right-hand
              side of the ‘=~’ operator specifies the growth model outcome and
              time scores. In the LGCM framework, the functional form of growth
              (e.g., linear) is defined by fixing the factor loadings of the
              growth model factors. The intercept factor remains constant for
              each individual across time; as such, factor loadings for the
              intercept <em>i</em> are fixed to the value of 1 at each
              measurement occassion. To define linear growth across the 4
              equidistant time points, time scores for the slope
              <em>s</em> growth factor are fixed at 0, 1, 2, and 3. Setting the
              time score at the first measurement occassion to zero anchors the
              latent intercept as “baseline” or “initial status”. Means and
              variances of the growth factors are estimated as the default, as
              is the growth factor covariance.
            </p>
            <div class="sourceCode" id="cb2">
              <pre
                class="sourceCode r fold-show"
              ><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="st">&#39; i =~ 1*y1 + 1*y2 + 1*y3 + 1*y4</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="st">           s =~ 0*y1 + 1*y2 + 2*y3 + 3*y4 &#39;</span></span></code></pre>
            </div>
            <p>
              The <em>growth()</em> function can be called to fit the
              <em>model</em> that we defined in the prior step.
            </p>
            <div class="sourceCode" id="cb3">
              <pre
                class="sourceCode r fold-show"
              ><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">growth</span>(model, <span class="at">data=</span>path<span class="sc">-</span>to<span class="sc">-</span>data)</span></code></pre>
            </div>
            <p>
              The <em>summary()</em> function can be called to provide an
              overview and show results of the fitted model.
            </p>
            <div class="sourceCode" id="cb4">
              <pre
                class="sourceCode r fold-show"
              ><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre>
            </div>
            <!--

The growth() function, is a wrapper function for the lavaan() function that automatically specifies fixed and free parameters for the latent growth model. Use of this function eliminates several additional coding steps such as having to constrain a subset of observed intercepts to zero and specifying that latent means are to be freely estimated. See [Example 5 full code] for additional details. 

fitMeasures

The *fitmeasures()* function can be called to provide a variety of model fit indices.

-->
          </div>
          <div id="abcd-example" class="section level3">
            <h3><span style="color: green">ABCD Example</span></h3>
            <p>
              “The goal of our current LGM is to assess the linear trajectory of
              GPA, with the question being, does the average student GPA in a
              particular school go up or down over time?”
            </p>
            <div class="sourceCode" id="cb5">
              <pre
                class="sourceCode r"
              ><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># LGCM for a continuous outcome [y], across four mesurement occassions</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="st">&#39; i =~ 1*Brain_T1 + 1*Brain_T2 + 1*Brain_T3 + 1*Brain_T4</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="st">           s =~ 0*Brain_T1 + 1*Brain_T2 + 2*Brain_T3 + 3*Brain_T4 &#39;</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">growth</span>(model, <span class="at">data=</span>mydata, <span class="at">meanstructure=</span><span class="cn">TRUE</span>, <span class="at">estimator =</span> <span class="st">&quot;MLR&quot;</span>, <span class="at">missing =</span> <span class="st">&quot;ML&quot;</span>)</span></code></pre>
            </div>
            <pre><code>## Warning in lav_data_full(data = data, group = group, cluster = cluster, : lavaan WARNING: some cases are empty and will be ignored:
##   44 429 636 682 1077 1174</code></pre>
            <pre><code>## Warning in lav_object_post_check(object): lavaan WARNING: some estimated lv
## variances are negative</code></pre>
            <div class="sourceCode" id="cb8">
              <pre
                class="sourceCode r"
              ><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>)</span></code></pre>
            </div>
            <pre><code>## lavaan 0.6-9 ended normally after 23 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         9
##                                                       
##                                                   Used       Total
##   Number of observations                          1326        1332
##   Number of missing patterns                        11            
##                                                                   
## Model Test User Model:
##                                                Standard      Robust
##   Test Statistic                                392.563     312.386
##   Degrees of freedom                                  5           5
##   P-value (Chi-square)                            0.000       0.000
##   Scaling correction factor                                   1.257
##        Yuan-Bentler correction (Mplus variant)                     
## 
## Model Test Baseline Model:
## 
##   Test statistic                              2563.464    1465.370
##   Degrees of freedom                                 6           6
##   P-value                                        0.000       0.000
##   Scaling correction factor                                  1.749
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.848       0.789
##   Tucker-Lewis Index (TLI)                       0.818       0.747
##                                                                   
##   Robust Comparative Fit Index (CFI)                         0.849
##   Robust Tucker-Lewis Index (TLI)                            0.818
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)              -5217.684   -5217.684
##   Scaling correction factor                                  1.578
##       for the MLR correction                                      
##   Loglikelihood unrestricted model (H1)      -5021.403   -5021.403
##   Scaling correction factor                                  1.463
##       for the MLR correction                                      
##                                                                   
##   Akaike (AIC)                               10453.368   10453.368
##   Bayesian (BIC)                             10500.077   10500.077
##   Sample-size adjusted Bayesian (BIC)        10471.488   10471.488
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.242       0.215
##   90 Percent confidence interval - lower         0.222       0.198
##   90 Percent confidence interval - upper         0.262       0.234
##   P-value RMSEA &lt;= 0.05                          0.000       0.000
##                                                                   
##   Robust RMSEA                                               0.241
##   90 Percent confidence interval - lower                     0.219
##   90 Percent confidence interval - upper                     0.264
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.238       0.238
## 
## Parameter Estimates:
## 
##   Standard errors                             Sandwich
##   Information bread                           Observed
##   Observed information based on                Hessian
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   i =~                                                                  
##     Brain_T1          1.000                               0.599    0.742
##     Brain_T2          1.000                               0.599    0.627
##     Brain_T3          1.000                               0.599    0.778
##     Brain_T4          1.000                               0.599    0.740
##   s =~                                                                  
##     Brain_T1          0.000                                  NA       NA
##     Brain_T2          1.000                                  NA       NA
##     Brain_T3          2.000                                  NA       NA
##     Brain_T4          3.000                                  NA       NA
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   i ~~                                                                  
##     s                 0.031    0.009    3.351    0.001    0.434    0.434
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .Brain_T1          0.000                               0.000    0.000
##    .Brain_T2          0.000                               0.000    0.000
##    .Brain_T3          0.000                               0.000    0.000
##    .Brain_T4          0.000                               0.000    0.000
##     i                 0.004    0.021    0.184    0.854    0.006    0.006
##     s                 0.008    0.006    1.528    0.126       NA       NA
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .Brain_T1          0.292    0.025   11.874    0.000    0.292    0.449
##    .Brain_T2          0.506    0.034   15.083    0.000    0.506    0.554
##    .Brain_T3          0.167    0.016   10.284    0.000    0.167    0.281
##    .Brain_T4          0.239    0.018   13.242    0.000    0.239    0.365
##     i                 0.359    0.034   10.494    0.000    1.000    1.000
##     s                -0.015    0.003   -4.441    0.000       NA       NA</code></pre>
            <div class="sourceCode" id="cb10">
              <pre
                class="sourceCode r"
              ><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extract information</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>mean_lv <span class="ot">&lt;-</span> <span class="fu">lavInspect</span>(fit, <span class="st">&quot;mean.lv&quot;</span>, <span class="at">add.labels =</span> <span class="cn">TRUE</span>, <span class="at">add.class =</span> <span class="cn">TRUE</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">list.by.group =</span> <span class="cn">TRUE</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">drop.list.single.group =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>cov_lv <span class="ot">&lt;-</span> <span class="fu">lavInspect</span>(fit, <span class="st">&quot;cov.lv&quot;</span>, <span class="at">add.labels =</span> <span class="cn">TRUE</span>, <span class="at">add.class =</span> <span class="cn">TRUE</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">list.by.group =</span> <span class="cn">TRUE</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">drop.list.single.group =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>intercept_var <span class="ot">&lt;-</span> cov_lv[<span class="dv">1</span>]</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>slope_var <span class="ot">&lt;-</span> cov_lv[<span class="dv">4</span>]</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>is_covary <span class="ot">&lt;-</span> cov_lv[<span class="dv">2</span>]</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>intercept_var</span></code></pre>
            </div>
            <pre><code>## [1] 0.3587796</code></pre>
            <div class="sourceCode" id="cb12">
              <pre
                class="sourceCode r"
              ><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>slope_var</span></code></pre>
            </div>
            <pre><code>## [1] -0.01450445</code></pre>
            <div class="sourceCode" id="cb14">
              <pre
                class="sourceCode r"
              ><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>is_covary</span></code></pre>
            </div>
            <pre><code>## [1] 0.03128647</code></pre>
            <div class="sourceCode" id="cb16">
              <pre
                class="sourceCode r"
              ><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>intercept_mean <span class="ot">&lt;-</span> mean_lv[<span class="dv">1</span>]</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>slope_mean <span class="ot">&lt;-</span> mean_lv[<span class="dv">2</span>]</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co">#lavInspect(fit, &quot;sampstat&quot;)</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co">#lavNames(fit, &quot;ov&quot; &quot;lv&quot;)</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co">#lavInspect(fit, &quot;mean.lv&quot;) #Alias: &quot;eeta&quot; [for E(eta)].</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="co">#lavInspect(fit, &quot;cor.lv&quot;)</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="co">#parTable(fit)</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="co">#varTable(fit)</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="co">#inspect(fit, what=&quot;cor.all&quot;)</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="co">#lavCor(fit)</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="co">#out &lt;- lavExport(fit, target = &quot;Mplus&quot;, export=FALSE)</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="co">#cat(out)</span></span></code></pre>
            </div>
            <pre><code>
Model Test User Model:
##                                                Standard      Robust
##   Test Statistic                                392.563     312.386
##   Degrees of freedom                                  5           5
##   P-value (Chi-square)                            0.000       0.000
</code></pre>
            <pre><code>User Model versus Baseline Model:

Comparative Fit Index (CFI)                    0.848       0.789
Tucker-Lewis Index (TLI)                       0.818       0.747
</code></pre>
            <pre><code>Root Mean Square Error of Approximation:
 
   RMSEA                                          0.242       0.215
</code></pre>
            <pre><code>Standardized Root Mean Square Residual:
 
   SRMR                                           0.238       0.238</code></pre>
            <!-- link to model diagnostics to evaluate in instances when fit is poor -->
            <p>
              The average baseline score (i.e., the mean intercept value) on the
              xxxxx measure is 0.003857 and the mean slope value is 0.008419.
              This means that the predicted xxxx score at the first measurement
              occasion (i.e., t=0) is 0.003857 and at each subsequent
              measurement occasion the xxxx score is expected to go up by
              0.008419 points. There is significant variability in individual’s
              xxxxx scores at baseline 0.3587796, p &lt; .xxx), as well as in
              their slope value -0.0145045, p &lt; .001), suggesting that the
              rate of change in xxxx was not the same for all children. Finally,
              the estimated negative covariance or 0.0312865, p &lt; .001)
              implies that the higher the starting score on xxxx, the weaker the
              increase in xxxxxx.
            </p>
            <div id="plots" class="section level4">
              <h4>Plots</h4>
              <div class="sourceCode" id="cb21">
                <pre
                  class="sourceCode r"
                ><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> new2, <span class="fu">aes</span>(<span class="at">x =</span> name, <span class="at">y =</span> value, <span class="at">group =</span> id_s))</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">fun =</span> mean, <span class="at">shape =</span> <span class="dv">17</span>, <span class="at">size =</span> <span class="dv">3</span>)<span class="sc">+</span><span class="fu">theme_bw</span>()</span></code></pre>
              </div>
              <pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
              <figure>
                <img
                  src="lsem-3_files/figure-html/growth%20model%20plots-1.png"
                  style=""
                />
                <figcaption></figcaption>
              </figure>
              <div class="sourceCode" id="cb23">
                <pre
                  class="sourceCode r"
                ><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#+ facet_grid(. ~ sex)</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co">#+ facet_wrap(~id_s)</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(new2, <span class="fu">aes</span>(<span class="at">x=</span>name, <span class="at">y=</span>value, <span class="at">group=</span><span class="dv">1</span>))<span class="sc">+</span><span class="fu">geom_jitter</span>(<span class="at">height =</span> <span class="dv">0</span>, <span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>)<span class="sc">+</span><span class="fu">geom_point</span>(<span class="at">alpha=</span><span class="fl">0.5</span>)<span class="sc">+</span><span class="fu">stat_summary</span>(<span class="at">fun=</span>mean, <span class="at">colour=</span><span class="st">&quot;red&quot;</span>, <span class="at">geom=</span><span class="st">&quot;line&quot;</span>, <span class="at">size =</span> <span class="dv">3</span>)<span class="sc">+</span><span class="fu">theme_bw</span>() <span class="co"># draw a mean line in the data</span></span></code></pre>
              </div>
              <figure>
                <img
                  src="lsem-3_files/figure-html/growth%20model%20plots-2.png"
                  style=""
                />
                <figcaption></figcaption>
              </figure>
              <div class="sourceCode" id="cb24">
                <pre
                  class="sourceCode r"
                ><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#shape = male, </span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co">#linetype = male</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co">#geom_line(aes(linetype = male), size = 1)</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="do">## load the grid package for the unit function to adjust the legend width</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co">#require(grid)</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="co">#theme(legend.key.width = unit(1, &quot;cm&quot;)) + theme_bw() + scale_linetype(name = &quot;Sex&quot;</span></span></code></pre>
              </div>
            </div>
            <div id="tables" class="section level4">
              <h4>Tables</h4>
              <div class="sourceCode" id="cb25">
                <pre
                  class="sourceCode r"
                ><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mydata)</span></code></pre>
              </div>
              <pre><code>## # A tibble: 6 x 38
##    id_s site_id fam_id        sex  age2 eduPar    IQ     White  AfrAmer     Hisp
##   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl+lbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl+lbl&gt; &lt;dbl+lb&gt; &lt;dbl+lb&gt;
## 1  1003      NA   4720 1 [Male]      10     19    53 1 [White] 0 [Non-~ 0 [Non-~
## 2  1009      11   8321 1 [Male]      10     11    36 0 [Non-W~ 0 [Non-~ 0 [Non-~
## 3  1032      12   1860 1 [Male]       9     14    45 0 [Non-W~ 1 [AfrA~ 0 [Non-~
## 4  1050       6   8784 1 [Male]       9     18    NA 0 [Non-W~ 0 [Non-~ 0 [Non-~
## 5  1053      11   8323 1 [Male]       9     13    48 1 [White] 0 [Non-~ 0 [Non-~
## 6  1056      11   8324 0 [Female]     9     15    35 1 [White] 0 [Non-~ 0 [Non-~
## # ... with 28 more variables: Other &lt;dbl+lbl&gt;, G_DBD &lt;dbl+lbl&gt;,
## #   G_CDCU &lt;dbl+lbl&gt;, G_CD &lt;dbl+lbl&gt;, Brain_T1 &lt;dbl&gt;, Brain_T2 &lt;dbl&gt;,
## #   Brain_T3 &lt;dbl&gt;, Brain_T4 &lt;dbl&gt;, Al_OFC &lt;dbl&gt;, Al_VS &lt;dbl&gt;, Ar_insl &lt;dbl&gt;,
## #   Ar_amyg &lt;dbl&gt;, Ar_ACC &lt;dbl&gt;, Ar_DS &lt;dbl&gt;, Ar_OFC &lt;dbl&gt;, Ar_VS &lt;dbl&gt;,
## #   Ol_insl &lt;dbl&gt;, Ol_amyg &lt;dbl&gt;, Ol_ACC &lt;dbl&gt;, Ol_DS &lt;dbl&gt;, Ol_OFC &lt;dbl&gt;,
## #   Ol_VS &lt;dbl&gt;, Or_insl &lt;dbl&gt;, Or_amyg &lt;dbl&gt;, Or_ACC &lt;dbl&gt;, Or_DS &lt;dbl&gt;,
## #   Or_OFC &lt;dbl&gt;, Or_VS &lt;dbl&gt;</code></pre>
              <p>Start with the ‘intercepts’:</p>
              <pre><code>Intercepts:
                   Estimate  Std.Err  Z-value  P(&gt;|z|)
                       
    i                 0.487    0.048   10.072    0.000
    s                 0.267    0.045    5.884    0.000</code></pre>
              <pre><code>Covariances:
                   Estimate  Std.Err  Z-value  P(&gt;|z|)
  i ~~                                                
    s                 0.226    0.050    4.512    0.000
Variances:
                   Estimate  Std.Err  Z-value  P(&gt;|z|)
    outcome0          0.287    0.041    6.924    0.000
    outcome1          0.219    0.021   10.501    0.000
    outcome2          0.185    0.027    6.748    0.000
    outcome3          0.357    0.065    5.485    0.000
    i                 0.977    0.076   12.882    0.000
    s                 0.969    0.065   14.841    0.000</code></pre>
            </div>
          </div>
        </div>
        <div id="section" class="section level2 unnumbered">
          <h2 class="unnumbered"></h2>
          <p>
            <br />
            <br />
          </p>
          <hr />
        </div>
        <div
          id="lgcm-w-time-varying-covariates"
          class="section level2 tabset tabset-fade"
          style="color: black"
        >
          <h2 class="tabset tabset-fade" style="color: black">
            5.2: LGCM w/ Time-Varying Covariates
          </h2>
          <p>
            <br />
            test
          </p>
          <div id="brief-overview" class="section level3">
            <h3><span style="color: orange">Brief Overview</span></h3>
            <p>test</p>
          </div>
          <div id="diagram-1" class="section level3">
            <h3><span style="color: red">Diagram</span></h3>
            <div
              id="htmlwidget-ab71f1cbbaa3b88f7237"
              style="width: 504px; height: 504px"
              class="grViz html-widget"
            ></div>
            <script
              type="application/json"
              data-for="htmlwidget-ab71f1cbbaa3b88f7237"
            >
              {
                "x": {
                  "diagram": "\ndigraph narc {\n\n  # a \"graph\" statement\n  graph [overlap = true, fontsize = 12]\n\n  # nodes for observed and latent\n  node [shape = circle, fontname = Helvetica]\n  \"Intercept\"; \"Slope\";\n  \n  node [shape = box, fontname = Helvetica]\n  t1; t2; t3; t4;\n\n  # edges\n  \"Intercept\"->\"t1\" \"Intercept\"->\"t2\" \"Intercept\"->\"t3\" \"Intercept\"->\"t4\"\n  \"Slope\"->\"t1\" \"Slope\"->\"t2\" \"Slope\"->\"t3\" \"Slope\"->\"t4\"\n}",
                  "config": { "engine": "dot", "options": null }
                },
                "evals": [],
                "jsHooks": []
              }
            </script>
          </div>
          <div id="code" class="section level3">
            <h3><span style="color: blue">Code</span></h3>
            <div class="sourceCode" id="cb29">
              <pre
                class="sourceCode r"
              ><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># a linear growth model with a time-varying covariate</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="st">  # intercept and slope with fixed coefficients</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="st">    i =~ 1*Brain_T1 + 1*Brain_T2 + 1*Brain_T3 + 1*Brain_T4</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="st">    s =~ 0*Brain_T1 + 1*Brain_T2 + 2*Brain_T3 + 3*Brain_T4</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="st">  # regressions</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="st">    i ~ sex + eduPar</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="st">    s ~ sex + eduPar</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="st">  # time-varying covariates</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="st">    Brain_T1 ~ G_CD</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="st">    Brain_T2 ~ IQ</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="st">    Brain_T3 ~ age2</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="st">    Brain_T4 ~ White</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">growth</span>(model, <span class="at">data =</span> mydata)</span></code></pre>
            </div>
            <pre><code>## Warning in lav_object_post_check(object): lavaan WARNING: some estimated lv
## variances are negative</code></pre>
            <div class="sourceCode" id="cb31">
              <pre
                class="sourceCode r"
              ><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre>
            </div>
            <pre><code>## lavaan 0.6-9 ended normally after 53 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        17
##                                                       
##                                                   Used       Total
##   Number of observations                          1175        1332
##                                                                   
## Model Test User Model:
##                                                       
##   Test statistic                               371.515
##   Degrees of freedom                                21
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   i =~                                                
##     Brain_T1          1.000                           
##     Brain_T2          1.000                           
##     Brain_T3          1.000                           
##     Brain_T4          1.000                           
##   s =~                                                
##     Brain_T1          0.000                           
##     Brain_T2          1.000                           
##     Brain_T3          2.000                           
##     Brain_T4          3.000                           
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   i ~                                                 
##     sex              -0.056    0.043   -1.320    0.187
##     eduPar           -0.001    0.008   -0.155    0.877
##   s ~                                                 
##     sex               0.010    0.011    0.914    0.361
##     eduPar           -0.000    0.002   -0.099    0.921
##   Brain_T1 ~                                          
##     G_CD              0.013    0.018    0.691    0.489
##   Brain_T2 ~                                          
##     IQ               -0.000    0.000   -0.568    0.570
##   Brain_T3 ~                                          
##     age2              0.004    0.002    1.713    0.087
##   Brain_T4 ~                                          
##     White             0.065    0.031    2.114    0.034
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##  .i ~~                                                
##    .s                 0.024    0.007    3.558    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Brain_T1          0.000                           
##    .Brain_T2          0.000                           
##    .Brain_T3          0.000                           
##    .Brain_T4          0.000                           
##    .i                 0.061    0.142    0.428    0.668
##    .s                -0.005    0.038   -0.133    0.894
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Brain_T1          0.264    0.019   13.835    0.000
##    .Brain_T2          0.458    0.021   21.660    0.000
##    .Brain_T3          0.164    0.010   16.187    0.000
##    .Brain_T4          0.226    0.015   15.366    0.000
##    .i                 0.326    0.025   13.255    0.000
##    .s                -0.012    0.003   -4.006    0.000</code></pre>
          </div>
          <div id="code-commentary" class="section level3">
            <h3><span style="color: green">Code Commentary</span></h3>
            <p>test test test</p>
          </div>
        </div>
        <div id="section-1" class="section level2 unnumbered">
          <h2 class="unnumbered"></h2>
          <p>
            <br />
            <br />
          </p>
          <hr />
        </div>
        <div
          id="lgcm-antecedent-predictors"
          class="section level2 tabset tabset-fade"
          style="color: black"
        >
          <h2 class="tabset tabset-fade" style="color: black">
            5.3: LGCM Antecedent Predictors
          </h2>
          <p>
            <br />
            test test test
          </p>
          <div id="brief-overview-1" class="section level3">
            <h3><span style="color: orange">Brief Overview</span></h3>
          </div>
          <div id="diagram-2" class="section level3">
            <h3><span style="color: red">Diagram</span></h3>
          </div>
          <div id="code-1" class="section level3">
            <h3><span style="color: blue">Code</span></h3>
          </div>
          <div id="code-commentary-1" class="section level3">
            <h3><span style="color: green">Code Commentary</span></h3>
          </div>
        </div>
        <div id="section-2" class="section level2 unnumbered">
          <h2 class="unnumbered"></h2>
          <p>
            <br />
            <br />
          </p>
          <hr />
        </div>
        <div
          id="lgcm-predicting-a-distal-outcome"
          class="section level2 tabset tabset-fade"
          style="color: black"
        >
          <h2 class="tabset tabset-fade" style="color: black">
            5.4: LGCM Predicting a Distal Outcome
          </h2>
          <p>
            <br />
            test test test
          </p>
          <p>
            The prior section introduced the fundamental latent growth model
            with an intercept and linear growth factor. This model sufficiently
            addresses the question of whether the linear trajectory is
            increasing, decreasing or flat over time. In our example, we found
            that GPA increases by on average for every one semester increase in
            time. Other researchers may be interested in finding casual (using
            the word loosely) predictors of this linear trajectory. For example,
            we found that the trajectory of GPA increases over time, but does
            gender predict this trend? More specifically, are there gender
            differences in either the starting GPA (intercept factor) or the
            growth trajectory (slope factor)? To find out, we would need to
            include an observed predictor of the latent mean and slope terms.
          </p>
          <div id="brief-overview-2" class="section level3">
            <h3><span style="color: orange">Brief Overview</span></h3>
          </div>
          <div id="diagram-3" class="section level3">
            <h3><span style="color: red">Diagram</span></h3>
          </div>
          <div id="code-2" class="section level3">
            <h3><span style="color: blue">Code</span></h3>
          </div>
          <div id="code-commentary-2" class="section level3">
            <h3><span style="color: green">Code Commentary</span></h3>
            <hr />
            <hr />
          </div>
        </div>
        <div
          id="continue-to-latent-transition-analysis-lta"
          class="section level2"
        >
          <h2>
            <a href="lsem-4.html" class="continue-link"
              >Continue to Latent Transition Analysis (LTA)</a
            >
          </h2>
        </div>
      </article>
      <!-- End Tailwind Typography -->
    </div>
    <!-- End custom layout -->

    <!-- include-after -->
    <!-- End include-after -->
  </body>
</html>
